import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-black dark:bg-gray-800 dark:text-white">
        <h1>Welcome to SC2 Build Order Manager</h1>

        <Link className="link" href="/submit-build">
          Submit a new Build
        </Link>
        <Link className="link" href="/races">
          View Builds
        </Link>
      </main>
    </>
  );
};

export default HomePage;
